repos:

  - repo: https://github.com/ambv/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.12
        exclude: >
          (?x)^(
            scripts/gen-docs-index|
          )$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        exclude: deploy/
      - id: debug-statements
      - id: detect-private-key
      - id: fix-encoding-pragma
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        entry: markdownlint --ignore .github/*.md

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.84.0
    hooks:
      - id: cfn-python-lint
        files: deploy/